
_G.Settings.AutoFarmCakePrince = false -- true / false Auto Farm Cake Prince
_G.Settings.IgnoreSpawnCake = false -- true / false Ignore Spawn Cake
_G.Settings.AutoBuddySword = false -- true / false Auto Buddy Sword
_G.Settings.EnabledHopBuddy = false -- true / false Enabled Hop Buddy
_G.Settings.AutoHallowSycthe = false -- true / false Auto Hallow Sycthe
_G.Settings.EnabledHallowSycthe = false -- true / false Enabled Hallow Sycthe
_G.Settings.AutoFarmBone = false -- true / false Auto Farm Bone
_G.Settings.EnabledRandomSurprise = false -- true / false Enabled Random Surprise
_G.Settings.AutoEliteHunter = false -- true / false Auto Elite Hunter
_G.Settings.EnabledHopElite = false -- true / false Enabled Hop Elite
_G.Settings.SelectMaterials = "" -- true / false  Your Select Materials "Leather","Magma Ore","Angel Wings","Radioactive Material","Scrap Metal","Demonic Wisp","Vampire Fang","Mini Tusk","Fish Tail","Gunpowder","Dragon Scale","Conjured Cocoa","Mystic Droplet"
_G.Settings.AutoFarmMaterials = false -- true / false Auto Farm Materials
_G.Settings.AutoTushita = false -- true / false Auto Tushita
_G.Settings.EnabledHopTushita = false -- true / false Enabled Hop Tushita
_G.Settings.AutoTushitaQuest = false -- true / false Auto Tushita Quest
_G.Settings.AutoYamaQuest = false -- true / false Auto Yama Quest
_G.Settings.AutoCDK = false -- true / false AutoCDK [ When Finish All Quest ]
_G.Settings.AutoSoulGuitar = false -- true / false Auto Soul Guitar
_G.Settings.EnabledHopSoulGuitar = false -- true / false Enabled Hop SoulGuitar
_G.Settings.AutoFindFullMoon = false -- true / false Auto Find FullMoon
_G.Settings.AutoDoughDungeon = true -- true / false Auto Dough Dungeon
_G.Settings.AutoPhoeDungeon = false -- true / false Auto Phoe Dungeon
_G.Settings.AutoDevilFruits = false -- true / false Auto Devil Fruits
getgenv().Key = "MARU-R0MNI-4ID-JC1SZ-6FF-8F18" getgenv().id = "865458556786311218" getgenv().Script_Mode = "Kaitun_Script" loadstring(game:HttpGet(("https://raw.githubusercontent.com/xshiba/MaruBitkub/main/Mobile.lua"), true))()
